export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const ACQUIRE_USERNAME_SUCCESS = 'ACQUIRE_USERNAME_SUCCESS';
export const ACQUIRE_USERNAME_FAIL = 'ACQUIRE_USERNAME_FAIL';
