# Generated by Django 4.0.2 on 2022-04-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.priority'),
        ),
    ]
