# Generated by Django 4.0.2 on 2022-04-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='level',
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.priority'),
        ),
    ]
