# Generated by Django 4.0.2 on 2022-06-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_todo_level_alter_todo_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='level',
            new_name='title',
        ),
    ]
