# Generated by Django 4.0.2 on 2022-03-17 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='lastModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
