# Generated by Django 4.0.2 on 2022-03-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_todo_lastmodified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='lastModified',
        ),
    ]
