# Generated by Django 4.0.2 on 2022-03-17 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_todo_lastmodified'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='lastModified',
            field=models.DateTimeField(default=datetime.date(2022, 3, 17)),
        ),
    ]
