# Generated by Django 4.0.2 on 2022-03-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_todo_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='lastModified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
