# Generated by Django 4.0.2 on 2022-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_todo_completed_alter_todo_lastmodified'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High Priority'), (2, 'Moderate Priority'), (3, 'Low Priority')], default=2),
        ),
    ]
