# Generated by Django 4.0.2 on 2022-03-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='primaryCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category'),
        ),
    ]
