# Generated by Django 4.0.2 on 2022-03-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_todo_primarycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='primaryCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
