# Generated by Django 4.0.2 on 2022-03-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_todo_primarycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High Priority'), (2, 'Moderate Priority'), (3, 'Low Priority')], default=2, null=True),
        ),
    ]
