# Generated by Django 4.0.2 on 2022-04-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.priority'),
        ),
    ]
