# Generated by Django 4.0.2 on 2022-04-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_todo_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.priority'),
        ),
    ]
