# Generated by Django 4.0.2 on 2022-04-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_todo_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='level',
        ),
    ]
